apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        apps: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image : gcr.io/$PROJECT_ID/gcp-project-71513:latest
        ports: 
        - containerPort: 5000
        env:
          - name: PORT
            value:  "5000"